#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
  name = "nvimcraft"
  email = "260064684+nvimcraft@users.noreply.github.com"

[ui]
  pager = "delta"
  editor = "nvim"
  bookmark-list-sort-keys = ["name"]
  tag-list-sort-keys = ["name"]
  relative-timestamps = true
  color = "always"
  diff-formatter = ":git"
  graph.style = "square"
  log-word-wrap = true

[diff.git]
  context = 3

[colors]
  commit_id = { fg = "#a7c080", bg = "#2f383e", bold = true }
  change_id = { reverse = true, dim = false, italic = true }
